"""Deploy means export, not proxy (UPGRADE_V4.md M14.4).

SPEC.md section 3 excludes any gateway that carries other applications' traffic, and that
exclusion stands: Tokop measures, it does not sit in the request path. So the Deploy control
produces artifacts a team applies themselves — the rewritten prompt as a diff, the operating
point as configuration, and the routing rule as code they can read before they run it.

Every artifact is generated from the report, so what is exported is what was proven. A config
file typed by hand beside a result is a config file that stops matching it.
"""

from __future__ import annotations

import difflib
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Literal

Artifact = Literal["prompt-diff", "cascade-config", "routing-rule"]
ARTIFACTS: tuple[Artifact, ...] = ("prompt-diff", "cascade-config", "routing-rule")

#: Extensions by artifact, so a written file opens in the right editor mode.
_SUFFIX: dict[Artifact, str] = {
    "prompt-diff": ".patch",
    "cascade-config": ".json",
    "routing-rule": ".py",
}


class ExportError(ValueError):
    """An artifact was asked for that this report cannot produce."""


@dataclass(frozen=True)
class ExportResult:
    artifact: Artifact
    path: Path
    text: str
    note: str

    def as_dict(self) -> dict[str, Any]:
        return {
            "artifact": self.artifact,
            "path": str(self.path),
            "bytes": len(self.text.encode("utf-8")),
            "note": self.note,
        }


def _pipeline_text(workload: Any, pipeline_id: str) -> str:
    """Every block of a pipeline's prompt, in the order the provider sees them."""
    spec = workload.pipeline(pipeline_id)
    lines: list[str] = []
    for role, blocks in (("system", spec.system), ("user", spec.user)):
        for block in blocks:
            label = block.label or role
            breakpoint = f"  [cache: {block.cache}]" if block.cache else ""
            lines.append(f"### {role}: {label}{breakpoint}")
            lines.extend(block.text.splitlines())
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def prompt_diff(payload: Any, workload: Any) -> tuple[str, str]:
    """A unified diff from the pipeline in production to the one the proof recommends."""
    proof = payload["proof"]
    before_id = proof["baseline"]["pipeline"]
    after_id = _candidate_prompt(payload)
    before = _pipeline_text(workload, before_id)
    after = _pipeline_text(workload, after_id)
    diff = "\n".join(
        difflib.unified_diff(
            before.splitlines(),
            after.splitlines(),
            fromfile=f"{before_id} (running today)",
            tofile=f"{after_id} (recommended)",
            lineterm="",
        )
    )
    note = (
        f"{before_id} to {after_id}. Cost per successful task "
        f"${float(proof['baseline']['cost_per_successful_task']['point']):.5f} to "
        f"${float(proof['candidate']['cost_per_successful_task']['point']):.5f}; "
        f"{proof['verdict']['display']}."
    )
    return diff + "\n", note


def _candidate_prompt(payload: Any) -> str:
    """Which pipeline's prompt the candidate actually runs.

    A cascade routes between tiers of one prompt, so the prompt to export is the cascade's base
    pipeline rather than the cascade id, which names no prompt at all.
    """
    candidate = str(payload["proof"]["candidate"]["pipeline"])
    if candidate in payload["pipelines"]:
        return candidate
    base = payload["cascade"].get("base_pipeline")
    if base in payload["pipelines"]:
        return str(base)
    raise ExportError(
        f"no prompt to export: {candidate} is not a pipeline and the cascade names no base"
    )


def _tier_rows(payload: Any) -> list[dict[str, Any]]:
    """The tiers in escalation order, each with the model it runs and the score it must clear."""
    return list(payload["cascade"]["tiers"])


def cascade_config(payload: Any) -> tuple[str, str]:
    """The operating point, as configuration rather than as prose."""
    cascade = payload["cascade"]
    proof = payload["proof"]
    choice = cascade["scorer_choice"]
    rows = _tier_rows(payload)
    config = {
        "$comment": (
            "Generated by `tokop export`. The operating point this report proved, not a "
            "suggestion: changing a threshold here invalidates the verdict below."
        ),
        "workload": payload["workload"]["id"],
        "base_pipeline": _candidate_prompt(payload),
        "scorer": {"kind": choice["scorer"], "samples": choice["k"], "method": choice["method"]},
        "tiers": [
            {
                "tier": row["tier"],
                "model_id": row["model_id"],
                "escalate_below": row["threshold"],
                "scarce": row["scarce"],
            }
            for row in rows
        ],
        "proved": {
            "verdict": proof["verdict"]["label"],
            "delta_accuracy_points": proof["delta_accuracy"]["point"] * 100,
            "margin_points": proof["verdict"]["margin"] * 100,
            "n": proof["candidate"]["n"],
            "evidence": payload["evidence"]["grade"],
            "price_snapshot": payload["provenance"]["price_snapshot_id"],
            "origin": payload["provenance"]["origin"],
        },
    }
    note = (
        f"{len(rows)} tiers, thresholds "
        + ", ".join(f"{row['threshold']:.2f}" for row in rows)
        + f", scorer {choice['label']}."
    )
    return json.dumps(config, indent=2, sort_keys=True, default=str) + "\n", note


def routing_rule(payload: Any) -> tuple[str, str]:
    """The routing decision as code, in the order the cascade actually evaluates it."""
    rows = _tier_rows(payload)
    choice = payload["cascade"]["scorer_choice"]
    lines = [
        '"""The routing rule this report proved, as code.',
        "",
        "Generated by `tokop export`; do not edit by hand. `score` is the probability that the",
        f"tier answers the task correctly, from {choice['label']}:",
        f"{choice['method']}.",
        "",
        "Escalation order is cheapest first. A tier answers when its score clears its threshold;",
        "the last tier answers whatever reaches it, which is why it has no threshold to clear.",
        '"""',
        "",
        "from collections.abc import Callable",
        "",
        f"WORKLOAD = {payload['workload']['id']!r}",
        "TIERS = [",
    ]
    for index, row in enumerate(rows):
        last = index == len(rows) - 1
        threshold = None if last else float(row["threshold"])
        lines.append(f"    ({row['tier']!r}, {row['model_id']!r}, {threshold!r}),")
    lines += [
        "]",
        "",
        "",
        "def route(task: str, score: Callable[[str, str], float]) -> str:",
        '    """The model id to send this task to."""',
        "    for tier, model_id, threshold in TIERS:",
        "        if threshold is None or score(task, tier) >= threshold:",
        "            return model_id",
        "    return TIERS[-1][1]",
        "",
    ]
    note = (
        f"escalates {' -> '.join(str(row['tier']) for row in rows)}, "
        f"deciding with {choice['label']}."
    )
    return "\n".join(lines), note


_BUILDERS: dict[str, Any] = {
    "cascade-config": cascade_config,
    "routing-rule": routing_rule,
}


def export(payload: Any, artifact: Artifact, out: Path, workload: Any = None) -> ExportResult:
    """Write one artifact, and say what it is."""
    if artifact not in ARTIFACTS:
        raise ExportError(f"unknown artifact {artifact!r}; choose from {', '.join(ARTIFACTS)}")
    if artifact == "prompt-diff":
        if workload is None:
            raise ExportError("a prompt diff needs the workload the prompts come from")
        text, note = prompt_diff(payload, workload)
    else:
        text, note = _BUILDERS[artifact](payload)
    path = out / f"{payload['workload']['id']}-{artifact}{_SUFFIX[artifact]}"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)
    return ExportResult(artifact=artifact, path=path, text=text, note=note)
